### ISSUE TITLE
Error con 'pydelicious'

### ISSUE THREAD

**Issue by geratarra** [uson-ia/sistemas-de-recomendacion#1]
Estoy batallando un poco con la API de delicious, al parecer cuando haces:
`pydelicious.get_popular('programmin')`
si te lanza links, pero en la key `'user'`, del diccionario que lanza, esta vacia..
por alguna razon no me da el usuario que publico el link, por lo tanto no funcionan
como deberian los metodos del archivo `delicious_rec.py`. Si lo prueban y si les funciona
comenten como lo hicieron, hagan su respectivo commit y cierren el issue.
Si no, creo que esto no seria tanto problema, podemos continuar y hacer nuestro dataset
con Movielens o con la propuesta de @chunkzer de la base de datos de Amazon

**Comment by FcoManueel** [comment]
La búsqueda de `pydelicious` lleva al repo de la librería, la cual al parecer ya no tiene soporte y es muy vieja (https://code.google.com/p/pydelicious/).

En el código fuente (https://code.google.com/p/pydelicious/source/browse/trunk/pydelicious/__init__.py) podemos ver que la request para la función get_popular la hace a la siguiente url: `http://del.icio.us/rss/popular/{tag}`

Así que me puse a checar la API del feed de delicious (https://delicious.com/rss), y al parecer ese tipo de request ya no se puede:
- Ya no se pueden conseguir feeds por `popular`
- La url para conseguir bookmarks por tags (e.g. `programming`) es http://feeds.delicious.com/v2/json/tag/programming
  Pero en efecto, **omiten el nombre del autor** (el campo llamado "a") en la respuesta.
  [ Sé que lo omiten porque tienen otro endpoint (http://feeds.delicious.com/v2/json/recent) en el que, si se busca el mismo bookmark, el nombre del autor si aparece. ] 

Así que el único endpoint (que encontré) que devuelve nombres de usuarios (para después buscar sus bookmarks) es el de `recent`, pero devuelve muy pocos resultados. Quizá `Movielens` convenga más.

Además veo que tanto @geratarra como @eduardoacye agregaron códice para cargar datos de Movielens, así que procederé a marcar el issue como cerrado :d

Happy Hacking

**Comment by geratarra** [comment]
Rifado manueluqui no se me ocurrió ver el source de pydelicious :o gracias por el aporte!!
